version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKER_VOLUMES/traefik/:/etc/traefik
networks:
  proxy:
